### PR TITLE
Adding rep set to the BIOM table

### PR DESCRIPTION
**Pull request by josenavas**
This add the notion of a representative set to the BIOM table. The representative set doesn't make sense outside of the attached BIOM table. With both of this files, we can validate that the representative set and the biom contain the same observation ids.

### CODE REVIEW

**Comment by antgonza** [comment]
👍 , @ElDeveloper, @mortonjt, could you take a look?

**Comment by antgonza** [comment]
@josenavas not sure what's up with the error.

**Comment by mortonjt** [comment]
Looks like travis is still failing.  Maybe extend the travis run from 10 min to 30 min?

**Comment by josenavas** [comment]
I'm not sure what is going on with the tests. They run in less than 10 seconds on my machine.

**Comment by antgonza** [comment]
Decided to rerun the test in travis and I think the new error (got it twice in a row) make more sense, can you check it? Also, perhaps worth removing the `--no-build-docs` ...

**Pull request merged**
